name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# manuálisan indítani
workflow_dispatch:

#időzített indítás
# schedule:
#   - cron: '04 10 * * * '

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: generate image tab
      run : |
      echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/borsodi-koppany/cicd-teszt:$IMAGE_TAB
        docker login ghcr.io -u borsodi-koppany -p ${{ secrets.GHCR_TOKEN }}
        docker push ghcr.io/borsodi-koppany/cicd-teszt:$IMAGE_TAB
 

